### ISSUE TITLE
How many ciphertexts are generated from coeffToSlots.

### ISSUE THREAD

**Issue by fionser** [snucrypto/HEAAN#13]
Hi, 
1. According to your Eurocrypt paper, coeffToSlots should generate two ciphertexts, since one ciphertext can contain only N/2 coeffcients in its slots. 
2. But the current implementation only generate single ciphertext.

So I am wondering it is an undocumented optimization here ?

Thanks.

**Comment by kimandrik** [comment]
Hi, 
Right it is an undocumented optimization. If we use not full number of slots in the ciphertext we can pack the result of coeffToSlots in one ciphertext instead of two

**Comment by fionser** [comment]
@kimandrik I see the trick.
