### ISSUE TITLE
How to perform a add operation after a mult operation?

### ISSUE THREAD

**Issue by Ldisi** [snucrypto/HEAAN#16]
Could someone help me to solve this problem? I mean if I want to perform a add operation, such as "addConst",after a mult operation,the add operation doesn't work at all.
like this : m1 = [1], m2 = [2] , m3=[3]  m1=m1*m2//m1=[2], then m1=m1+m3//m1still is [2]!!!
and I don't know why.

**Comment by kimandrik** [comment]
Hello, maybe after multiplication you need to rescale: 
enc(m1, logp), enc(m2,logp)

enc_(m1*m2, 2*logp) = enc(m1, logp) * enc(m_2, logp)
enc_(m1*m2, logp) = rescale (enc_(m1*m2, 2*logp), logp)
enc_(m1*m2, logp) + const(m3, logp) = enc(m1*m2 + m3, logp)

**Comment by HanKyoohyung** [comment]
Or you can do as follows:
mult(ctxt1, ctxt1, ctxt2); // ctxt1 is now encryption of m1 + m2
addConst(ctxt1, ctxt1, m3, **2 * logp**); // ctxt2 is now encryption of m1 + m2 + m3

Reason: the logp parameter becomes double after "mult" function.

**Comment by Ldisi** [comment]
THX you two! Please correct my code!
    complex<double> test1;
    Ciphertext* test1_ = scheme->encryptSingle(1, logp, logQ);    
    Ciphertext* test2_ = scheme->encryptSingle(2, logp, logQ);
    Ciphertext* test3_ = scheme->encryptSingle(3, logp, logQ);

    scheme->multAndEqual(test1_, test2_);
    scheme->reScaleToAndEqual(test1_,2*logp);
    scheme->addAndEqual(test1_,test2_,  logp);

    test1 = scheme->decryptSingle(secretKey, test1_);  cout<<" test1="<<real(test1)<<endl;

**Comment by HanKyoohyung** [comment]
complex<double> test1;
Ciphertext* test1_ = scheme->encryptSingle(1, logp, logQ);    
Ciphertext* test2_ = scheme->encryptSingle(2, logp, logQ);
Ciphertext* test3_ = scheme->encryptSingle(3, logp, logQ);

scheme->multAndEqual(test1_, test2_); 
scheme->reScaleToAndEqual(test1_,**logp**); 
scheme->addAndEqual(test1_,test2_,  logp);

test1 = scheme->decryptSingle(secretKey, test1_);  cout<<" test1="<<real(test1)<<endl;

**Comment by Ldisi** [comment]
what I get is a big number :     test1=6.76255e+87

**Comment by Ldisi** [comment]
And it's all my code:
#include "../src/HEAAN.h" 
#include<vector>

using namespace std;

int main() {
   
  // Parameters //
  long logN = 15;
  long logQ = 353;
  long logp = 30; 
  long slots = 1024; 
  long numThread = 8;
	
  // Construct and Generate Public Keys //
  TimeUtils timeutils;
  Ring* ring = new Ring(logN, logQ);
  SecretKey* secretKey = new SecretKey(ring);
  Scheme* scheme = new Scheme(secretKey, ring);      SchemeAlgo* algo = new SchemeAlgo(scheme);
  
  complex<double> test1;
  Ciphertext* test1_ = scheme->encryptSingle(1, logp, logQ);
  Ciphertext* test2_ = scheme->encryptSingle(2, logp, logQ);
  Ciphertext* test3_ = scheme->encryptSingle(3, logp, logQ);

  scheme->multAndEqual(test1_, test2_);
  scheme->reScaleToAndEqual(test1_,logp);
  scheme->addAndEqual(test1_,test2_);

  test1 = scheme->decryptSingle(secretKey, test1_); cout<<" test1="<<real(test1)<<endl;
    
    return 0;
}

**Comment by Ldisi** [comment]
And it's all my code:
#include "../src/HEAAN.h" 
#include<vector>

using namespace std;

int main() {
   
  // Parameters //
  long logN = 15;
  long logQ = 353;
  long logp = 30; 
  long slots = 1024; 
  long numThread = 8;
	
  // Construct and Generate Public Keys //
  TimeUtils timeutils;
  Ring* ring = new Ring(logN, logQ);
  SecretKey* secretKey = new SecretKey(ring);
  Scheme* scheme = new Scheme(secretKey, ring);      SchemeAlgo* algo = new SchemeAlgo(scheme);
  
  complex<double> test1;
  Ciphertext* test1_ = scheme->encryptSingle(1, logp, logQ);
  Ciphertext* test2_ = scheme->encryptSingle(2, logp, logQ);
  Ciphertext* test3_ = scheme->encryptSingle(3, logp, logQ);

  scheme->multAndEqual(test1_, test2_);
  scheme->reScaleToAndEqual(test1_,logp);
  scheme->addAndEqual(test1_,test2_);

  test1 = scheme->decryptSingle(secretKey, test1_); cout<<" test1="<<real(test1)<<endl;
    
    return 0;
}

**Comment by HanKyoohyung** [comment]
Oh the key part should be as follows:

scheme->multAndEqual(test1_, test2_);
scheme->reScaleByAndEqual(test1_,logp);
scheme->modDownByAndEqual(test2_,logp);
scheme->addAndEqual(test1_,test2_);

After rescale, modulus of ciphertext is reduced. For add, two input ciphertext should have the same modulus. For this reason, you need to use "modDownbyAndEqual" function. Sorry for confusing.

**Comment by Ldisi** [comment]
not at all, THX! ^--^

**Comment by Ldisi** [comment]
Hi，I have a further questions,I want to compute a value of polynomials, ie, f=a0+a1x+a2x^2+a3x^3+a4x^4,which could be simplified into four steps: 1)f=a3+a4x 2)f=a2+f*x 3)f=a1+f*x  4)f=a0+f*x  ,and my code is here:  
#include "../src/HEAAN.h" 
#include<vector>

using namespace std;

int main() {
   
  // Parameters //
  long logN = 15;
  long logQ = 353;
  long logp = 30; 
  long slots = 1024; 
  long numThread = 8;
	
  // Construct and Generate Public Keys //
  TimeUtils timeutils;
  Ring* ring = new Ring(logN, logQ);
  SecretKey* secretKey = new SecretKey(ring);
  Scheme* scheme = new Scheme(secretKey, ring);      SchemeAlgo* algo = new SchemeAlgo(scheme);
  
  complex<double> f_;Ciphertext* f;
  Ciphertext* a0 = scheme->encryptSingle(0, logp, logQ);
  Ciphertext* a1 = scheme->encryptSingle(1, logp, logQ);
  Ciphertext* a2 = scheme->encryptSingle(2, logp, logQ);
  Ciphertext* a3 = scheme->encryptSingle(3, logp, logQ);
  Ciphertext* a4 = scheme->encryptSingle(4, logp, logQ);
  Ciphertext* x = scheme->encryptSingle(10, logp, logQ);
  f = a4;
//step1：
  scheme->multAndEqual(f, x);
  scheme->reScaleByAndEqual(f,logp);
  scheme->modDownByAndEqual(a3,logp);
  scheme->addAndEqual(f,a3);               
  f_ = scheme->decryptSingle(secretKey, f); cout<<" f="<<real(f_)<<endl;
//step2：
  scheme->multAndEqual(f, x);
  scheme->reScaleByAndEqual(f,logp); 
  scheme->modDownByAndEqual(a2,logp);
  scheme->addAndEqual(f,a2);
  f_ = scheme->decryptSingle(secretKey, f); cout<<" f="<<real(f_)<<endl;
//step3：
  scheme->multAndEqual(f, x);
  scheme->reScaleByAndEqual(f,logp); 
  scheme->reScaleByAndEqual(f,logp);
  scheme->addAndEqual(f,a1);
  f_ = scheme->decryptSingle(secretKey, f); cout<<" f="<<real(f_)<<endl;
//step4：
  scheme->multAndEqual(f, x);
  scheme->reScaleByAndEqual(f,logp); 
  scheme->modDownByAndEqual(a0,logp);
  scheme->addAndEqual(f,a0);

  f_ = scheme->decryptSingle(secretKey, f); cout<<" f="<<real(f_)<<endl;
    
    return 0;
}
But I failed,the result is that:
#include "../src/HEAAN.h" 
using namespace std;
int main() {  
  // Parameters //
  long logN = 15;
  long logQ = 353;
  long logp = 30; 
  long slots = 1024; 
  long numThread = 8;
	
  // Construct and Generate Public Keys //
  TimeUtils timeutils;
  Ring* ring = new Ring(logN, logQ);
  SecretKey* secretKey = new SecretKey(ring);
  Scheme* scheme = new Scheme(secretKey, ring);      SchemeAlgo* algo = new SchemeAlgo(scheme);
  
  complex<double> f_;Ciphertext* f;
  Ciphertext* a0 = scheme->encryptSingle(0, logp, logQ);
  Ciphertext* a1 = scheme->encryptSingle(1, logp, logQ);
  Ciphertext* a2 = scheme->encryptSingle(2, logp, logQ);
  Ciphertext* a3 = scheme->encryptSingle(3, logp, logQ);
  Ciphertext* a4 = scheme->encryptSingle(4, logp, logQ);
  Ciphertext* x = scheme->encryptSingle(10, logp, logQ);
  f = a4;
//step1：
  scheme->multAndEqual(f, x);
  scheme->reScaleByAndEqual(f,logp);
  scheme->modDownByAndEqual(a3,logp);
  scheme->addAndEqual(f,a3);               
  f_ = scheme->decryptSingle(secretKey, f); cout<<" f="<<real(f_)<<endl;
//step2：
  scheme->multAndEqual(f, x);
  scheme->reScaleByAndEqual(f,logp); 
  scheme->modDownByAndEqual(a2,logp);
  scheme->addAndEqual(f,a2);
  f_ = scheme->decryptSingle(secretKey, f); cout<<" f="<<real(f_)<<endl;
//step3：
  scheme->multAndEqual(f, x);
  scheme->reScaleByAndEqual(f,logp); 
  scheme->reScaleByAndEqual(f,logp);
  scheme->addAndEqual(f,a1);
  f_ = scheme->decryptSingle(secretKey, f); cout<<" f="<<real(f_)<<endl;
//step4：
  scheme->multAndEqual(f, x);
  scheme->reScaleByAndEqual(f,logp); 
  scheme->modDownByAndEqual(a0,logp);
  scheme->addAndEqual(f,a0);

  f_ = scheme->decryptSingle(secretKey, f); cout<<" f="<<real(f_)<<endl;
    
    return 0;
}
But I failed ,my result is that : f=43,f=432,f=-4.23606e+69,f=4.37959e+60, the last two results are wrong.Could you someone tell me why and how,thanks!

**Comment by Ldisi** [comment]
My problem solved by change logp from 30 to 19, my result is that : f=43,f=431.999,f=4320.99 ,f=43209.9.  It's a little bit wrong, but I think it's acceptable.
