### ISSUE TITLE
what's the function of "modDownByAndEqual"?

### ISSUE THREAD

**Issue by Ldisi** [snucrypto/HEAAN#17]
scheme->multAndEqual(test1_, test2_);
scheme->reScaleByAndEqual(test1_,logp);
scheme->modDownByAndEqual(test2_,logp);
scheme->addAndEqual(test1_,test2_);
As it is, 
1. the logp parameter becomes double after "mult" function.
2. After rescale, modulus of ciphertext is reduced.  
3. For add, two input ciphertext should have the same modulus.
In my opinion,test1_'s modulus will be logp after scale. So why test2_ need modDownByAndEqual operation? Could someone tell me? THX!

**Comment by kimandrik** [comment]
When we ReScale we decrease both logq and logp. On the picture it looks like:
xxxxxxoooo -> xxxxxxoo  (we kind of removing least significant bits)

When we ModDown we decrease only logq. On the picture it looks like:
xxxxxxoooo -> xxxxoooo  (we kind of removing most significant bits)

We normally ModDown to make ciphertexts have same logq to be able to perform operations

Suppose you have three ciphertexts that looks like: 
xxxxxxxxoo (c1 and c2)

When we multiply two of them we have smth like:    
xxxxxxoooo (c1 * c2)

Then we ReScale it to have:                                             
xxxxxxoo (c1 * c2 with rescale)

The third ciphertext still has form: 
xxxxxxxxoo (c3)

So we ModDown it to same logq to add with the resulting ciphertext:
xxxxxxoo (c3 with mod down)

Now we can add them)

**Comment by Ldisi** [comment]
THX！
