### ISSUE TITLE
Summing elements of ciphertext

### ISSUE THREAD

**Issue by mayank26saxena** [snucrypto/HEAAN#21]
HElib has a function [totalSums](https://github.com/homenc/HElib/blob/663ae63ca17f58c42eda0ed4ffe79a321d6109ba/src/EncryptedArray.cpp) which finds the sum of the whole ciphertext array. Is there an equivalent function in HEAAN?

If there does not exist any such functionality currently, could you provide any guidance regarding how to develop such a function?

Thanks!

**Comment by fionser** [comment]
We can write the totalSum in HEAAN by simply "copying" the code from HElib.
1. long n = ea.szie() == nslots in HEAAN

```
void totalSums(const EncryptedArray& ea, Ctxt& ctxt)
{
  long n = ea.size();

  if (n == 1) return;

  Ctxt orig = ctxt;

  long k = NumBits(n);
  long e = 1;

  for (long i = k-2; i >= 0; i--) {
    Ctxt tmp1 = ctxt;
    ea.rotate(tmp1, e);
    ctxt += tmp1; // ctxt = ctxt + (ctxt >>> e)
    e = 2*e;

    if (bit(n, i)) {
      Ctxt tmp2 = orig;
      ea.rotate(tmp2, e);
      ctxt += tmp2; // ctxt = ctxt + (orig >>> e)
                    // NOTE: we could have also computed
                    // ctxt =  (ctxt >>> e) + orig, however,
                    // this would give us greater depth/noise
      e += 1;
    }
  }
}

```

**Comment by HanKyoohyung** [comment]
ctxt.n (number of slots) is always power of two in this library.

So you can write totalSum as follows:

void totalSum(Scheme &scheme, const Ciphertext &ctxt, Ciphertext &ctxt_out)
{
	long n = ctxt.n;
	ctxt_out = ctxt;
	for(long i = 1; i < n; i <<= 1)
	{
		Ciphertext rot;
		scheme.leftRotateFast(rot, ctxt_out, i);
		scheme.addAndEqual(ctxt_out, rot);
	}
}

I note that you need to generate rotation keys for "scheme.leftRotateFast(rot, ctxt_out, i);" part.

**Comment by mayank26saxena** [comment]
Thanks you! The function you have provided works. 

However, I am also getting a segmentation fault in the end.

**Comment by jayavanth** [comment]
@mayank26saxena I removed the line `ctxt_out = ctxt;` and did the rotate and add on `ctxt` and now it doesn't seg fault anymore

**Comment by mayank26saxena** [comment]
Thanks @jayavanth !

**Comment by sbajpeyi** [comment]
Hi,

I tried implementing this function but found that after a size of n=16, the decrypted output values do not make sense (all of order 1e71).
I have also found that the output is not always consistent - at the size where the function breaks, if I run the function twice in a row one time it will decrypt to the expected output values and one time it will decrypt to the incorrect large values I mentioned.

Do you have any idea why this may be happening?

Any feedback is appreciated. Thanks!
