### ISSUE TITLE
Setting parameters for Bootstrapping

### ISSUE THREAD

**Issue by mayank26saxena** [snucrypto/HEAAN#22]
I'm having trouble in setting up the parameters for using the following function:

```void Scheme::bootstrapAndEqual(Ciphertext& cipher, long logq, long logQ, long logT, long logI)```

- How should I determine the right value of logQ? Is there any formula for determining these parameters?
- Could you provide a small example of using this function? 

Thank you!

**Comment by kimandrik** [comment]
Hello, for logQ you set the maximum possible value used in Ciphertexts. For example use logQ from params.h. Parameter logI is normally 4, and for parameter logT you can check the paper https://eprint.iacr.org/2018/153.pdf (in the paper r = logT+logI)

In TestScheme there is an example testBootstrap (where Bootstrapping divided into parts to check the time for each of the parts)

**Comment by mayank26saxena** [comment]
Could you provide an example as to how one can find logQ for a given logq? Is there any relationship between the two? 

I have checked the example parameters mentioned in the code but they don't work for my data.

**Comment by kimandrik** [comment]
There is no relationship between logq and logQ. You should set logQ the largest possible value. For example in the paper https://eprint.iacr.org/2018/153.pdf you can use logN=16, logQ=1240 (at that time it was about 80 bits security)

**Comment by mayank26saxena** [comment]
Okay. I used the parameters from the paper and it works!
