### ISSUE TITLE
Test HEAAN library have some trouble

### ISSUE THREAD

**Issue by nankeep** [snucrypto/HEAAN#26]
After I "make" in /run and try to ./TestHEAAN, It shows some problems：
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_S_construct null not valid

**Comment by kimandrik** [comment]
Hello, your second argument should be one of "Encrypt, EncryptSingle, Add, Mult, iMult, RotateFast, Conjugate". You can run "./TestHEAAN Encrypt" for example.

**Comment by nankeep** [comment]
Thank you！ The test has passed.
