### ISSUE TITLE
Is there a way to find the modulus of the ciphertext?

### ISSUE THREAD

**Issue by jayavanth** [snucrypto/HEAAN#27]
Or is there a way I can estimate it based on what operations I'm doing? e.g. addition, multiplication?

**Comment by kimandrik** [comment]
Hello, ciphertext modulus bits is cipher.logq

**Comment by HanKyoohyung** [comment]
Ciphertext modulus is cipher.logq

and I want to note that in case of HEAAN, there is no plaintext modulus. It just do operations on complex field :)
