### ISSUE TITLE
Why is bootstrapping so sensitive to values of logp and logq?

### ISSUE THREAD

**Issue by jayavanth** [snucrypto/HEAAN#28]
Is there a rule I should follow to set logp and logq (and other parameters) while bootstrapping?

In this example:
```
    long logq = 200;
    long logp = 50;
    long logSlots = 1;
    long logQ=1200, logT=2, logI=4;

    srand(time(NULL));
    SetNumThreads(8);
    TimeUtils timeutils;
    Ring ring;
    SecretKey secretKey(ring);
    Scheme scheme(secretKey, ring);

    timeutils.start("Key generating");
    scheme.addBootKey(secretKey, logSlots, logq + logI);
    timeutils.stop("Key generated");

    double c = 0.08123123;

    long slots = (1 << logSlots);
    complex<double>* mvec = EvaluatorUtils::randomComplexArray(slots);

    Ciphertext cipher, cipherv1, res;
    scheme.encrypt(cipher, mvec, slots, logp, logq);

    for(long i=0; i<slots ; i++)
        mvec[i] = c + mvec[i];

    cout << "cipher logq before: " << cipher.logq << " logp " << cipher.logp << endl;
    scheme.addConstAndEqual(cipher, c, logp);
    scheme.bootstrapAndEqual(cipher, logq, logQ, logT, logI);
    cout << "cipher logq after: " << cipher.logq << " logp " << cipher.logp << endl;

    complex<double>* dvec = scheme.decrypt(secretKey, cipher);
    StringUtils::compare(mvec, dvec, slots, "boot");
```
with the current logq and logp values, the program crashes with a segmentation fault during bootstrapAndEqual.

If I set logp=23 and logq=40, it works fine. Why doesn't boostrapping work with higher logq values? I've found that when I evaluate a polynomial without bootstrapping, it needs higher logq values to work.

**Comment by kimandrik** [comment]
Hello, in bootstrapping we try to increase logq -> logQ. But we have to evaluate some circuit while bootstrapping so we can only increase logq -> logQ', where logQ' is smaller than logQ. I'm not sure how much it is smaller (you can estimate it by looking at the code, maybe it is about logQ-12*logq.) So if you logq is 200, we cannot do bootstrapping. We try to set initial logq about 40, so after bootstrapping our logq is about 600-700

**Comment by jayavanth** [comment]
So, every time I'm bootstrapping after some operations, I have to do a `modDownTo` to get the `logq` down to ~40, right?

**Comment by kimandrik** [comment]
In Scheme.cpp->bootstrapAndEqual->line 1194 we are doing modDownTo to logq ~40, so you need just to set logq in the bootstrapAndEqual around 40. And your logp should be smaller than logq (So the case logq =200, logp = 50 if you want to use bootstrapping with parameters logp=23 and logq=40, you can reScaleBy 27 bits first and then modDownTo 40 bits)

**Comment by jayavanth** [comment]
Ah that makes sense. Basically, I'm trying to bootstrap Sigmoid function and I don't know how many operations I can do, before I can `bootstrapAndEqual`. Right now, I can't bootstrap after `SchemeAlgo::function` with any `degree` parameter (even with 1), because it crashes the `bootstrapAndEqual` function. However, I've noticed that I can bootstrap after I do something like 6 mixed multiplications and additions with a constant. 

Is there some kind of heuristic for the number of operations that I can do before bootstrapping?

**Comment by kimandrik** [comment]
So suppose you start with parameters (logp,logq)=(30, 1200)
- after multiplication of two ciphertexts (30, 1200) x (30, 1200) you get (60, 1200)
- then you can rescale by 30 bits, you get (30, 1170)
- then you can multiply again (30, 1170) x (3, 1170) you get (60, 1170). NOTE: if you have (30, 1170) and (30, 1200) you have to modDown second ciphertext by 30 bits to get  (30, 1170) and (30, 1170)
- then from (60, 1170) you can rescale again by 30 bits, you get (30, 1140), and so on
- at some point you get logq small, so you cannot make any operations, suppose (30, 60). Then you modDown by 20 bits to obtain (30, 40). Then you can bootstrapp and get (30, ~600), so now you can continue your operations. 

It means that if you do multiplications and rescalings properly your multiplication depth is about logq/logp before you need bootstrapping

**Comment by jayavanth** [comment]
Here's what I have. Looking at the polynomial `SIGMOID` with degree `7`, I see at most 11 mult operations. This code crashes with a `segmentation fault (core dumped)` at `bootstrapAndEqual`


```
    long logq = 1200;  ///< Ciphertext Modulus
    long logp = 23;    ///< Real message will be quantized by multiplying 2^40
    long logSlots = 4; ///< log2(The number of slots)
    long logT = 2;     //< this means that we use Taylor approximation in [-1/T,1/T] with double angle fomula
    long logI = 4;
    long logQ = 1200;

    srand(time(NULL));
    SetNumThreads(8);
    TimeUtils timeutils;
    Ring ring;
    SecretKey secretKey(ring);
    Scheme scheme(secretKey, ring);
    SchemeAlgo algo(scheme);

    timeutils.start("Key generating");
    scheme.addBootKey(secretKey, logSlots, logq + logI);
    timeutils.stop("Key generated");

    long slots = (1 << logSlots);
    complex<double>* mval = EvaluatorUtils::randomComplexArray(slots);
    complex<double>* x = EvaluatorUtils::randomComplexArray(slots);
    Ciphertext cipher;
    scheme.encrypt(cipher, mval, slots, logp, logq);

    // sigmoid truth
    for (long i = 0; i < slots; ++i) {
        x[i] = exp(mval[i]) / (1. + exp(mval[i]));
    }

    complex<double>* dval = new complex<double>[slots];

    Ciphertext result;
    cout << "cipher logq before: " << cipher.logq << " logp " << cipher.logp << endl;
    algo.function(result, cipher, SIGMOID, logp, 7);
    cout << "cipher logq after polynom: " << result.logq << " logp " << result.logp << endl;

    scheme.bootstrapAndEqual(result, 40, logQ, logT, logI);

    std::cout << "decrypt to compare" << std::endl;
    dval = scheme.decrypt(secretKey, result);
    StringUtils::compare(x, dval, slots, "boot");
```

**Comment by jayavanth** [comment]
Found the bug. The last argument should be `40 + logI` instead of `logq + logI`
