### ISSUE TITLE
Inverse of ciphertext - Part 2

### ISSUE THREAD

**Issue by jayavanth** [snucrypto/HEAAN#31]
Is there a way to get inverse for a wider range of input?

#2 suggests increasing the range by increasing the range by sacrificing precision. I was wondering if there were any updates to the library for inverse or division since then. I'm looking into [Matrin et al.](https://eprint.iacr.org/eprint-bin/getfile.pl?entry=2015/1195&version=20151216:042322&file=1195.pdf) to see if I can do it for a wider range.

Also, what do the functions `idiv`, and all the functions that start with `i` do?

**Comment by kimandrik** [comment]
imult and idiv are multiplication and division by imaginary unit i ( as far as I remember we used them in bootstrapping )
Unfortunately, there was no update on the inverse function.

**Comment by jayavanth** [comment]
I wanted to increase the range of the function beyond [0.5, 1.5]. I was looking at [Matrin et al.](https://eprint.iacr.org/eprint-bin/getfile.pl?entry=2015/1195&version=20151216:042322&file=1195.pdf) referenced in your paper and they say that the restriction is

<a href="https://www.codecogs.com/eqnedit.php?latex=b&space;\epsilon&space;\left&space;\[&space;2^{l-1},&space;2^{l}&space;\right&space;\)" target="_blank"><img src="https://latex.codecogs.com/gif.latex?b&space;\epsilon&space;\left&space;\[&space;2^{l-1},&space;2^{l}&space;\right&space;\)" title="b \epsilon \left \[ 2^{l-1}, 2^{l} \right \)" /></a>

So, we can only have inverses for ranges like 0.5-1, 0.25, 0.5 etc. Is that correct?

**Comment by kimandrik** [comment]
In our implementation, we can increase the interval from [0.5,1.5] to [delta, 2-delta] as far as I remember by using more number of iterations. I'm not sure if we can do better than this as for very small value the inverse is very big, and in HEAAN we try to work with not very big values. For too big values the inverse is too small, so it could be blurred with the error. Maybe you can better adapt Matrin et al. method to HEAAN, or some other methods, we did not update this part of the library

**Comment by jayavanth** [comment]
Thanks!
