### ISSUE TITLE
Tests fail: undefined reference to `NTL::operator<<(std::ostream&, NTL::ZZ const&)'

### ISSUE THREAD

**Issue by yurivict** [snucrypto/HEAAN#40]

**Comment by yurivict** [comment]
The library has an unresolved symbol:
```
$ nm ./work/HEAAN-2.1-39-gb2edd4c/HEAAN/lib/libHEAAN.so | c++filt | grep operator
                 U NTL::operator<<(std::basic_ostream<char, std::char_traits<char> >&, NTL::ZZ const&)
```

**Comment by gamma-2017** [comment]
Have you compiled and installed NTL properly? NTL is not HEAAN nor part of it, but needed.

**Comment by yurivict** [comment]
> Have you compiled and installed NTL properly?

It is linked with libntl.so but this symbol isn't present there.

**Comment by gamma-2017** [comment]
Well, for me it works.
Have you added ntl after heaan or before? Order matters.

**Comment by yurivict** [comment]
after

**Comment by yurivict** [comment]
This doesn't happen any more.
