### ISSUE TITLE
Is there a way to calculate square root?

### ISSUE THREAD

**Issue by TaihouKai** [snucrypto/HEAAN#45]
I am sorry if I missed anything, but I didn't find any function about square root in `Scheme.cpp`.

**Comment by swanhong** [comment]
HEAAN(and other HE libraries) only supports addition and multiplication. If you want to evaluate non-polynomial functions such as square root, inverse, etc, you should express them as a polynomial(approximately if it is impossible). [CKK+18](https://eprint.iacr.org/2019/417.pdf) may help you.

**Comment by macknight** [comment]
> HEAAN(and other HE libraries) only supports addition and multiplication. If you want to evaluate non-polynomial functions such as square root, inverse, etc, you should express them as a polynomial(approximately if it is impossible). [CKK+18](https://eprint.iacr.org/2019/417.pdf) may help you.

Hi, how about deviation of a bunch of data?
Is deviation also a non-polynomial function?

BR
