### ISSUE TITLE
How to install HEAAN Library

### ISSUE THREAD

**Issue by omeravci372742** [snucrypto/HEAAN#50]
Hello, I am trying to work on Homomorphic Encryption so I try to install and use HEAAN Library.
In their github page, they tell us to create static library  libHEAAN.a with make all comment. When I try this I got errors saying M_PI is not defined in this scope. After I redifing pi number as desired then I get an error with sctruct definition timeval then I include 
<sys/time.h> in Timeutilites.h then I finally get  libHEAAN.a but then I can not add library to any of my compilers or I can not compile from ubuntu command. I always get same respond, the file or directory can not found. What can I do? I am so desperate for help.

**Comment by swanhong** [comment]
Have you installed NTL library? It may be helpful if you show me the detail of the error log.

**Comment by omeravci372742** [comment]
I installed the NTL yes, I will send the error log today.

3 Ara 2020 Per 09:41 tarihinde Seungwan Hong <notifications@github.com>
şunu yazdı:

**Comment by omeravci372742** [comment]
But basically, I upload the library folder in MinGw but when I try to add
header include <HEEAN.h> and compile my code, it gives the error no
directory or file found.

3 Ara 2020 Per 11:00 tarihinde Ömer Avci <omeravci372742@gmail.com> şunu
yazdı:

**Comment by swanhong** [comment]
HEAAN library doesn't support Windows OS, so if you are trying with Windows, I cannot help to fix the error. It would be better to build with Mac or Ubuntu.

**Comment by omeravci372742** [comment]
Oh thank you so much, this will save a lot of time.

7 Ara 2020 Pzt 04:36 tarihinde Seungwan Hong <notifications@github.com>
şunu yazdı:
