### ISSUE TITLE
How to compute security level when setting bigger ciphertext modulus?

### ISSUE THREAD

**Issue by WeiBenqiang** [snucrypto/HEAAN#51]
`  long logq = 300; ///< Ciphertext modulus (this value s**hould be <=** logQ in "scr/Params.h")`
But in scr/Params.h", `static const long logQ = 800; // 128-bit security`
Therefore， my question is when I need a bigger ciphertext modulus，i.e. 2000,
how to compute security level or set other parameters given security level? THX!

**Comment by imtiyazuddin** [comment]
I have the same doubt, please !!!
If we see sagemathcell implementation of tester for checking security levels for given paramters, as we increase logq for same n value, it says security level also increases. is this true??
If so why not just set n to 1024 and increase only logq to meet different application requirements.

**Comment by bencrts** [comment]
> ` long logq = 300; ///< Ciphertext modulus (this value s**hould be <=** logQ in "scr/Params.h")`
> But in scr/Params.h", `static const long logQ = 800; // 128-bit security`
> Therefore， my question is when I need a bigger ciphertext modulus，i.e. 2000,
> how to compute security level or set other parameters given security level? THX!

You could use the [LWE Estimator](https://bitbucket.org/malb/lwe-estimator/src/master/) to compute the security levels. There are some usage examples on the repository -- note that for sparse secrets you will need to pass `secret_distribution = ((-1,1),h)`, where `h` is the Hamming weight of the secret you are using.

> I have the same doubt, please !!!
> If we see sagemathcell implementation of tester for checking security levels for given paramters, as we increase logq for same n value, it says security level also increases. is this true??
> If so why not just set n to 1024 and increase only logq to meet different application requirements.

Generally, for a fixed value of `(n, sigma, secret_distribution)`, increasing `q` will lower the security level. This behaviour can be seen in the [HE Security Standard](http://homomorphicencryption.org/wp-content/uploads/2018/11/HomomorphicEncryptionStandardv1.1.pdf) (see e.g. Table 1 on page 26/27).

**Comment by swanhong** [comment]
In addition to @bencrts's answer, you can find the concrete parameters in [2021/039](https://eprint.iacr.org/2021/039.pdf) that considering the most recent LWE attacks for the ternary sparse secrets.

**Comment by imtiyazuddin** [comment]
what is the value of alpha in HEAAN library??
